---

- name: create_local_repo | Create {{ item.repo }} local repo
  uri:
    url: "{{ pulp_api_server }}/pulp/api/v3/repositories/"
    user: "{{ pulp_admin_user }}"
    password: "{{ pulp_default_admin_password }}"
    method: POST
    body: {"name":"{{ item.repo }}"}
    force_basic_auth: yes
    status_code: 201,400
    body_format: json
  changed_when: repo.status == 201
  register: repo

- name: create_local_repo | Get repo {{ item.repo }} HREF
  uri:
    url: "{{ pulp_api_server }}/pulp/api/v3/repositories/?name={{ item.repo }}"
    user: "{{ pulp_admin_user }}"
    password: "{{ pulp_default_admin_password }}"
    method: GET
    force_basic_auth: yes
    status_code: 200
  register: repo

- set_fact:
    repo_tasks: []
    pkg_list: []

- name: create_local_repo | Upload rpm packages for repo {{ item.repo }}
  include_tasks: upload_package.yml
  vars:
    repo_href: "{{ repo.json.results[0]._href }}"
    repo_name: "{{ item.repo }}"
    base_path: "{{ item.base_path }}"
    pkg_dir: "{{ item.pkg_dir }}"
  loop: "{{ item.packages }}"
  loop_control:
    loop_var: package

- name: create_local_repo | Add rpm package to repo {{ item.repo }}
  include_tasks: add_package.yml
  vars:
    repo_href: "{{ repo.json.results[0]._href }}"
    repo_name: "{{ item.repo }}"
  loop: "{{ pkg_list }}"
  loop_control:
    loop_var: package

- debug:
    var: repo_tasks

- name: create_local_repo | Waiting end of tasks
  include_tasks: wait_task.yml
  vars:
  loop: "{{ repo_tasks }}"
  loop_control:
    loop_var: task_href

- name: create_local_repo | {{ item.repo }} Publish and Distribute
  include_tasks: publish_distribute.yml
