---

- name: remove_remote | Get remote {{ item.remote }} HREF
  uri:
    url: "{{ pulp_api_server }}/pulp/api/v3/remotes/rpm/rpm/?name={{ item.remote }}"
    user: admin
    password: "{{ pulp_default_admin_password }}"
    method: GET
    force_basic_auth: y
    status_code: 200
  register: remote

- name: remove_remote | Remove remote {{ item.remote }}
  uri:
    url: "{{ pulp_api_server }}{{ remote.json.results[0]._href }}"
    user: admin
    password: "{{ pulp_default_admin_password }}"
    method: DELETE
    force_basic_auth: y
    status_code: 202
  changed_when: result.status == 202
  register: result
  when: remote.json.results[0] is defined
