---

- name: config | Get repo {{ item.repo }} HREF
  uri:
    url: "{{ pulp_api_server }}/pulp/api/v3/repositories/?name={{ item.repo }}"
    user: admin
    password: "{{ pulp_default_admin_password }}"
    method: GET
    force_basic_auth: yes
    status_code: 200
    return_content: yes
  register: repo

- name: config | Remove repo {{ item.repo }}
  uri:
    url: "{{ pulp_api_server }}{{ repo.json.results[0]._href }}"
    user: admin
    password: "{{ pulp_default_admin_password }}"
    method: DELETE
    force_basic_auth: yes
    status_code: 202
    return_content: yes
  changed_when: result.status == 202
  register: result
  when: repo.json.results[0] is defined

- name: config | Remove orphans artifacts
  uri:
    url: "{{ pulp_api_server }}/pulp/api/v3/orphans/"
    user: admin
    password: "{{ pulp_default_admin_password }}"
    method: DELETE
    force_basic_auth: yes
    status_code: 202
    return_content: yes
  changed_when: result.status == 202
  register: result
  when: repo.json.results[0] is defined


