---

- name: remove_repo | Get repo {{ item.repo }} HREF
  uri:
    url: "{{ pulp_api_server }}/pulp/api/v3/repositories/?name={{ item.repo }}"
    user: "{{ pulp_admin_user }}"
    password: "{{ pulp_default_admin_password }}"
    method: GET
    force_basic_auth: y
    status_code: 200
  register: repo

- block:

    - name: remove_repo | Remove repo {{ item.repo }}
      uri:
        url: "{{ pulp_api_server }}{{ repo.json.results[0]._href }}"
        user: "{{ pulp_admin_user }}"
        password: "{{ pulp_default_admin_password }}"
        method: DELETE
        force_basic_auth: y
        status_code: 202
      changed_when: result.status == 202
      register: result

    - name: remove_repo | Remove orphans artifacts
      uri:
        url: "{{ pulp_api_server }}/pulp/api/v3/orphans/"
        user: "{{ pulp_admin_user }}"
        password: "{{ pulp_default_admin_password }}"
        method: DELETE
        force_basic_auth: y
        status_code: 202
      changed_when: result.status == 202
      register: result

    - name: create_local_repo | Waiting end of tasks
      include_tasks: wait_task.yml
      vars:
        - task_href: "{{ result.json.task }}"

  when: repo.json.results[0] is defined
