---

- name: remove_repo | Get repo {{ item.repo }} HREF
  uri:
    url: "{{ pulp_api_server }}/pulp/api/v3/repositories/?name={{ item.repo }}"
    user: admin
    password: "{{ pulp_default_admin_password }}"
    method: GET
    force_basic_auth: y
    status_code: 200
  register: repo

- name: remove_repo | Remove repo {{ item.repo }}
  uri:
    url: "{{ pulp_api_server }}{{ repo.json.results[0]._href }}"
    user: admin
    password: "{{ pulp_default_admin_password }}"
    method: DELETE
    force_basic_auth: y
    status_code: 202
  changed_when: result.status == 202
  register: result
  when: repo.json.results[0] is defined

- name: remove_repo | Remove orphans artifacts
  uri:
    url: "{{ pulp_api_server }}/pulp/api/v3/orphans/"
    user: admin
    password: "{{ pulp_default_admin_password }}"
    method: DELETE
    force_basic_auth: y
    status_code: 202
  changed_when: result.status == 202
  register: result
  when: repo.json.results[0] is defined
