---

- name: wait_task | Waiting end of task
  uri:
    url: "{{ pulp_api_server }}{{ task_href }}"
    user: "{{ pulp_admin_user }}"
    password: "{{ pulp_default_admin_password }}"
    method: GET
    force_basic_auth: y
    status_code: 200
  register: task
  until: task.json.state != "running" and task.json.state != "waiting"
  changed_when: "'completed' in task.json.state"
  retries: 120
  delay: 10

- name: wait_task | Check end task status
  uri:
    url: "{{ pulp_api_server }}{{ task_href }}"
    user: "{{ pulp_admin_user }}"
    password: "{{ pulp_default_admin_password }}"
    method: GET
    force_basic_auth: y
    status_code: 200
  register: task
  failed_when:
    - "(not 'completed' in task.json.state)"
    - "(not 'already exists' in task.json.error.traceback)"
