#!/bin/bash

#!/bin/bash

# Usage info
show_help() {
cat << EOF
Usage: ${0##*/} [-h] --repo REPO_NAME --pub  PUB_NAME [--remote REMOTE_NAME] [--port PORT]
    -h                   Display this help and exit
    --repo REPO_NAME     Name of the local repo
    --pub  PUB_NAME      Name of the publisher
    --remote REMOTE_NAME (Optional) Name of the remote repo which was sync with local one
    --port PORT          (Optional) API port number default to $PORT
EOF
}

PORT=":24817"

for i in "$@"; do
    case $i in
        --repo)
        REPO_NAME="$2"
        shift # past argument
        shift # past value
        ;;
        --pub)
        PUB_NAME="$2"
        shift # past argument
        shift # past value
        ;;
        --remote)
        REMOTE_NAME="$2"
        shift # past argument
        shift # past value
        ;;
          --port)
        PORT="$2"
        shift # past argument
        shift # past value
        ;;
        -h|-\?|--help)
        show_help    # Display usage 
        exit
        ;;
     esac
done

if [ -z ${REPO_NAME+x} ]; then
   echo "A variable is unset";
   show_help
   exit
fi

if [ -z ${PUB_NAME+x} ]; then
   echo "A variable is unset";
   show_help
   exit
fi

REPO_HREF=$(http $PORT/pulp/api/v3/repositories/rpm/rpm/ | jq -r --arg REPO_NAME "$REPO_NAME" '.results[] | select(.name == $REPO_NAME) | .pulp_href')
echo "REPO $REPO_HREF"

if [ ! -z ${REMOTE_NAME+x} ]; then
  REMOTE_HREF=$(http $PORT/pulp/api/v3/remotes/rpm/rpm/ | jq -r --arg REMOTE_NAME "$REMOTE_NAME" '.results[] | select(.name == $REMOTE_NAME) | .pulp_href')
  echo "REMOTE $REMOTE_HREF"
fi

PUBLISHER_HREF=$(http $PORT/pulp/api/v3/publishers/rpm/rpm/ | jq -r --arg PUB_NAME "$PUB_NAME" '.results[] | select(.name == $PUB_NAME) | .pulp_href')
echo "PUBLISHER $PUBLISHER_HREF"

PUBLICATION_HREF=$(http $PORT/pulp/api/v3/publications/ | jq -r --arg PUBLISHER_HREF "$PUBLISHER_HREF" '.results[] | select(.publisher == $PUBLISHER_HREF) | .pulp_href')
echo "PUBLICATION $PUBLICATION_HREF"

DISTRI_HREF=$(http $PORT/pulp/api/v3/distributions/ | jq -r --arg PUBLICATION_HREF "$PUBLICATION_HREF" '.results[] | select(.publication == $PUBLICATION_HREF) | .pulp_href')
echo "DISTRIBUTION $DISTRI_HREF"
