#!/bin/bash

# Usage info
show_help() {
cat << EOF
Usage: ${0##*/} [-h] --repo REPO_NAME --remote REMOTE_NAME --href [--port PORT]
    -h                   Display this help and exit
    --repo REPO_NAME     Name of the local repo
    --remote REMOTE_NAME Name of the remote repo to be sync with local one
    --href REMOTE_URL    URL of the remote repository
    --port PORT          (Optional) API port number default to $PORT
    --policy POLICY      (Optional) immediate (default), on_demand
EOF
}

wait_task() {

    echo $2
    state=$(http $PORT$1 | jq -r '.state')
    while [ "$state" == "running" ]; do
        sleep 10
        state=$(http $PORT$1 | jq -r '.state')
        echo $state
    done

    if [ "$state" == "failed" ]; then
        echo "TASK FAILED"
        http $PORT$1
        exit 1
    fi
}

# set default values
PORT=":24817"
POLICY="immediate"

for i in "$@"; do
    case $i in
        --repo)
        REPO_NAME="$2"
        shift # past argument
        shift # past value
        ;;
        --remote)
        REMOTE_NAME="$2"
        shift # past argument
        shift # past value
        ;;
        --href)
        REMOTE_URL="$2"
        shift # past argument
        shift # past value
        ;;
         --port)
        PORT="$2"
        shift # past argument
        shift # past value
        ;;
        -h|-\?|--help)
        show_help    # Display usage 
        exit
        ;;
     esac
done

# Check variables
if [ -z ${REPO_NAME+x} ]; then
   echo "A variable is unset";
   show_help
   exit 1
fi
if [ -z ${REMOTE_NAME+x} ]; then
   echo "A variable is unset";
   show_help
   exit 1
fi
if [ -z ${REMOTE_URL+x} ]; then
   echo "A variable is unset";
   show_help
   exit 1
fi

REPO_HREF=$(http $PORT/pulp/api/v3/repositories/rpm/rpm/ | jq -r --arg REPO_NAME "$REPO_NAME" '.results[] | select(.name == $REPO_NAME) | .pulp_href')
if [ ! $REPO_HREF ]; then
    # Create a new local repository and get its HREF
    REPO_HREF=$(http POST $PORT/pulp/api/v3/repositories/rpm/rpm/ name="$REPO_NAME" | jq -r '.pulp_href')
else
    echo REPO_HREF found
fi

REMOTE_HREF=$(http $PORT/pulp/api/v3/remotes/rpm/rpm/ | jq -r --arg REMOTE_NAME "$REMOTE_NAME" '.results[] | select(.name == $REMOTE_NAME) | .pulp_href')
if [ ! $REMOTE_HREF ]; then
    # Add a new remote repository and get its HREF
    REMOTE_HREF=$(http POST $PORT/pulp/api/v3/remotes/rpm/rpm/ name="$REMOTE_NAME" url="$REMOTE_URL" policy="$POLICY" | jq -r '.pulp_href')

    # Synchronize repos
    TASK=$(http POST $PORT${REMOTE_HREF}sync/ repository=$REPO_HREF | jq -r '.task')
    wait_task $TASK "Waiting for sync to finish ..."
else
    echo REMOTE_HREF found
fi

PUBLISHER_HREF=$(http $PORT/pulp/api/v3/publishers/rpm/rpm/ | jq -r --arg REMOTE_NAME "$REMOTE_NAME" '.results[] | select(.name == $REMOTE_NAME) | .pulp_href')
if [ ! $PUBLISHER_HREF ]; then
    # Create a rpm Publisher and get its HREF
    PUBLISHER_HREF=$(http POST $PORT/pulp/api/v3/publishers/rpm/rpm/ name="$REMOTE_NAME" | jq -r '.pulp_href')
else
    echo PUBLISHER_HREF found
fi

PUBLICATION_HREF=$(http $PORT/pulp/api/v3/publications/rpm/rpm/ | jq -r --arg PUBLISHER_HREF "$PUBLISHER_HREF" '.results[] | select(.publisher == $PUBLISHER_HREF) | .pulp_href')
if [ ! $PUBLICATION_HREF ]; then
    # Create a Publication of local repository and get its local HREF
    TASK=$(http POST $PORT${PUBLISHER_HREF}publish/ repository="$REPO_HREF" | jq -r '.task')
    wait_task $TASK "Waiting for Publication to finish ..."

    # Get HREF of Local Publication
    PUBLICATION_HREF=$(http $PORT/pulp/api/v3/publications/rpm/rpm/ | jq -r --arg PUBLISHER_HREF "$PUBLISHER_HREF" '.results[] | select(.publisher == $PUBLISHER_HREF) | .pulp_href')
else
    echo PUBLICATION_HREF found
fi

DISTRI_HREF=$(http $PORT/pulp/api/v3/distributions/rpm/rpm/ | jq -r --arg PUBLICATION_HREF "$PUBLICATION_HREF" '.results[] | select(.publication == $PUBLICATION_HREF) | .pulp_href')
if [ ! $DISTRI_HREF ]; then
    # Distribute the repo
    http POST $PORT/pulp/api/v3/distributions/ name="$REPO_NAME" base_path="$REMOTE_NAME" publication=$PUBLICATION_HREF
else
    echo DISTRI_HREF found
fi

exit 0
