#!/bin/bash

#!/bin/bash

# Usage info
show_help() {
cat << EOF
Usage: ${0##*/} [-h] --repo REPO_NAME [--remote REMOTE_NAME] [--port PORT]
    -h                   Display this help and exit
    --repo REPO_NAME     Name of the local repo
    --remote REMOTE_NAME (Optional) Name of the remote repo which was sync with local one
    --port PORT          (Optional) API port number default to $PORT
EOF
}

PORT=":24817"

for i in "$@"; do
    case $i in
        --repo)
        REPO_NAME="$2"
        shift # past argument
        shift # past value
        ;;
        --remote)
        REMOTE_NAME="$2"
        shift # past argument
        shift # past value
        ;;
          --port)
        PORT="$2"
        shift # past argument
        shift # past value
        ;;
        -h|-\?|--help)
        show_help    # Display usage 
        exit
        ;;
     esac
done

if [ -z ${REPO_NAME+x} ]; then
   echo "A variable is unset";
   show_help
   exit
fi

REPO_HREF=$(http $PORT/pulp/api/v3/repositories/rpm/rpm/ | jq -r --arg REPO_NAME "$REPO_NAME" '.results[] | select(.name == $REPO_NAME) | .pulp_href')

if [ ! -z ${REMOTE_NAME+x} ]; then
  REMOTE_HREF=$(http $PORT/pulp/api/v3/remotes/rpm/rpm/ | jq -r --arg REMOTE_NAME "$REMOTE_NAME" '.results[] | select(.name == $REMOTE_NAME) | .pulp_href')
  echo "REMOTE $REMOTE_HREF"
fi

if [ ! -z ${REMOTE_NAME+x} ]; then
    echo "removing REMOTE $REMOTE_HREF"
    http DELETE $PORT$REMOTE_NAME
fi

echo "removing REPO $REPO_HREF"
http DELETE $PORT$REPO_HREF
