#!/bin/bash

#!/bin/bash

# Usage info
show_help() {
cat << EOF
Usage: ${0##*/} [-h] --repo REPO_NAME --remote REMOTE_NAME [--port PORT]
    -h                   Display this help and exit
    --repo REPO_NAME     Name of the local repo
    --remote REMOTE_NAME Name of the remote repo to be sync with local one
    --port PORT          (Optional) API port number default to :8000
EOF
}

for i in "$@"; do
    case $i in
        --repo)
        REPO_NAME="$2"
        shift # past argument
        shift # past value
        ;;
        --remote)
        REMOTE_NAME="$2"
        shift # past argument
        shift # past value
        ;;
        --port)
        PORT="$2"
        shift # past argument
        shift # past value
        ;;
        -h|-\?|--help)
        show_help    # Display usage 
        exit
        ;;
     esac
done

if [ -z ${REPO_NAME+x} ]; then
   echo "A variable is unset";
   show_help
   exit
fi
if [ -z ${REMOTE_NAME+x} ]; then
   echo "A variable is unset";
   show_help
   exit
fi

PORT=${PORT-:8000}

export REPO_HREF=$(http $PORT/pulp/api/v3/repositories/ | jq -r --arg REPO_NAME "$REPO_NAME" '.results[] | select(.name=$REPO_NAME) | ._href')
export REMOTE_HREF=$(http $PORT/pulp/api/v3/remotes/rpm/rpm/ | jq -r --arg REMOTE_NAME "$REMOTE_NAME" '.results[] | select(.name=$REMOTE_NAME) | ._href')
export PUBLISHER_HREF=$(http $PORT/pulp/api/v3/publishers/rpm/rpm/ | jq -r --arg REMOTE_NAME "$REMOTE_NAME" '.results[] | select(.name=$REMOTE_NAME) | ._href')
export PUBLICATION_HREF=$(http $PORT/pulp/api/v3/publications/ | jq -r --arg PUBLISHER_HREF "$PUBLISHER_HREF" '.results[] | select(.publisher==$PUBLISHER_HREF) | ._href')
export DISTRI_HREF=$(http $PORT/pulp/api/v3/distributions/ | jq -r --arg PUBLICATION_HREF "$PUBLICATION_HREF" '.results[] | select(.publication==$PUBLICATION_HREF) | ._href')

echo "removing DISTRIBUTION"
http DELETE $PORT$DISTRI_HREF
echo "removing PUBLICATION"
http DELETE $PORT$PUBLICATION_HREF
echo "removing PUBLISHER"
http DELETE $PORT$PUBLISHER_HREF
echo "removing REMOTE"
http DELETE $PORT$REMOTE_HREF
echo "removing REPO"
http DELETE $PORT$REPO_HREF
